echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "I am learning Jenkins Triggers"
echo "Welcome to Young Minds"
echo "We are going very slow"
echo "Now I am expert in the Jenkins"
